config/routes.rb
M1c::Application.routes.draw do
  resources :picks

end

app/models/pick.rb
class Pick < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  # GET /picks
  # GET /picks.xml
  def index
    @picks = Pick.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @picks }
    end
  end

  # GET /picks/1
  # GET /picks/1.xml
  def show
    @pick = Pick.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pick }
    end
  end

  # GET /picks/new
  # GET /picks/new.xml
  def new
    @pick = Pick.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pick }
    end
  end

  # GET /picks/1/edit
  def edit
    @pick = Pick.find(params[:id])
  end

  # POST /picks
  # POST /picks.xml
  def create
    @pick = Pick.new(params[:pick])

    respond_to do |format|
      if @pick.save
        format.html { redirect_to(@pick, :notice => 'Pick was successfully created.') }
        format.xml  { render :xml => @pick, :status => :created, :location => @pick }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pick.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /picks/1
  # PUT /picks/1.xml
  def update
    @pick = Pick.find(params[:id])

    respond_to do |format|
      if @pick.update_attributes(params[:pick])
        format.html { redirect_to(@pick, :notice => 'Pick was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pick.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /picks/1
  # DELETE /picks/1.xml
  def destroy
    @pick = Pick.find(params[:id])
    @pick.destroy

    respond_to do |format|
      format.html { redirect_to(picks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>M1c</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/picks/_form.html.erb
<%= form_for(@pick) do |f| %>
  <% if @pick.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pick.errors.count, "error") %> prohibited this pick from being saved:</h2>

      <ul>
      <% @pick.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :round %><br />
    <%= f.text_field :round %>
  </div>
  <div class="field">
    <%= f.label :method %><br />
    <%= f.text_field :method %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/picks/edit.html.erb
<h1>Editing pick</h1>

<%= render 'form' %>

<%= link_to 'Show', @pick %> |
<%= link_to 'Back', picks_path %>

app/views/picks/index.html.erb
<h1>Listing picks</h1>

<table>
  <tr>
    <th>Round</th>
    <th>Method</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @picks.each do |pick| %>
  <tr>
    <td><%= pick.round %></td>
    <td><%= pick.method %></td>
    <td><%= link_to 'Show', pick %></td>
    <td><%= link_to 'Edit', edit_pick_path(pick) %></td>
    <td><%= link_to 'Destroy', pick, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pick', new_pick_path %>

app/views/picks/new.html.erb
<h1>New pick</h1>

<%= render 'form' %>

<%= link_to 'Back', picks_path %>

app/views/picks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Round:</b>
  <%= @pick.round %>
</p>

<p>
  <b>Method:</b>
  <%= @pick.method %>
</p>


<%= link_to 'Edit', edit_pick_path(@pick) %> |
<%= link_to 'Back', picks_path %>